### ISSUE TITLE
[feat]: token revocation

### ISSUE THREAD

**Issue by helloimalastair** [pilcrowonpaper/arctic#104]
Arctic currently supports generating/refreshing/verifying tokens, but would it be possible for it to support revoking those tokens as well(specifically [RFC7009](https://datatracker.ietf.org/doc/html/rfc7009))?

**Comment by pilcrowonpaper** [comment]
Can you move the feature request to Oslo? I'll add them here once we've implemented there

https://github.com/pilcrowOnPaper/oslo/issues

**Comment by helloimalastair** [comment]
[Done](https://github.com/pilcrowOnPaper/oslo/issues/65)
