### ISSUE TITLE
add `config_id` option to facebook provider

### ISSUE THREAD

**Issue by wouter173** [pilcrowonpaper/arctic#106]
The facebook OAuth api has an option for a `config_id` parameter instead of `scopes` when using it in the context of a ['Login for Business'](https://developers.facebook.com/docs/facebook-login/facebook-login-for-business/#invoke-a--login-dialog) instead of the user facing OAuth flow.

Although it is not an OAuth2 specced feature, I believe it adds value to the facebook provider.

**Comment by yutakobayashidev** [comment]
LINE also has custom parameters like bot_prompt. Do you have any good ideas for efficiently adding custom parameters?

https://developers.line.biz/ja/docs/line-login/link-a-bot/#redirect-users

**Comment by wouter173** [comment]
There are already providers that change up the creation of the authorization url. For example microsoft-entra-id adding a nonce, or okta having a default scope and setting the state param manually.

These do however not have extra arguments being passed to the function and I'm not sure that's the way arctic wants to be positioned as we can just add these parameters manually once the url has been created.

**Comment by pilcrowonpaper** [comment]
Any parameters outside of those defined in the OAuth 2.0 specs should be implemented user-side.

```ts
const url = provider.createAuthorizationURL();
url.searchParams.set("config_id", configId);
```
