### ISSUE TITLE
pass URL search params in `createAuthorizationURL` method

### ISSUE THREAD

**Issue by kravetsone** [pilcrowonpaper/arctic#116]
![image](https://github.com/pilcrowOnPaper/arctic/assets/57632712/4fc531db-11c0-428e-8773-53d5f85b1cd1)

Why it cannot be something like:

```ts
const url = await google.createAuthorizationURL(state, codeVerifier, {
	scopes: ["profile", "email"],
	access_type: "online"
});
```

**Comment by pilcrowonpaper** [comment]
Because I don't want to keep track of new and deprecated options. `URL.searchParams` is good enough
