### ISSUE TITLE
Feature request: Github App Provider

### ISSUE THREAD

**Issue by alex-way** [pilcrowonpaper/arctic#119]
It seems like the GitHub provider is expecting/using the Oauth app type. However, Github are now recommending github apps to be used in favour of oauth apps: https://docs.github.com/en/enterprise-cloud@latest/apps/overview#github-apps-and-oauth-apps

Relevant documentation for generating a user access token: https://docs.github.com/en/enterprise-cloud@latest/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app#using-the-device-flow-to-generate-a-user-access-token

**Comment by pilcrowonpaper** [comment]
Are you referring to GitHub Apps or device code login?

**Comment by hunvreus** [comment]
@pilcrowOnPaper I'd be interested in hearing how you think one should implement Oauth flow using a GitHub App (as opposed to a GitHub OAuth App)? Regular Oauth login, not device flow.

**Comment by pilcrowonpaper** [comment]
Sorry, I'm a bit confused what needs to be done to support GitHub Apps? Doesn't it just use the same OAuth 2.0 flow with the same endpoints?

**Comment by hunvreus** [comment]
Yes, I realized that 0.2 seconds after I posted this. It works the same for GitHub Apps and GitHub OAuth Apps.

**Comment by pilcrowonpaper** [comment]
Closing this unless there's a change that needs to be done by us

**Comment by hunvreus** [comment]
@pilcrowOnPaper Thanks for Lucia (and Arctic, and Oslo).

I switched [my Next.js project](https://github.com/pages-cms/pages-cms/tree/next) over from Auth.js and find it a lot more straightforward.
