### ISSUE TITLE
Unable to install Artic 

### ISSUE THREAD

**Issue by rexdavid** [pilcrowonpaper/arctic#121]
Not sure if anyone faced this issue before when install artic. Seems to be some sort of problem with artic dependencies.

command ran : **pnpm add artic** 

**error:**

../sqlite3@3.1.13/node_modules/sqlite3 install$ node-pre-gyp install --fallback-to-build
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@0.6.38
│ node-pre-gyp info using node@21.4.0 | linux | x64
│ node-pre-gyp info check checked for "/home/rexdavid/Mounts/devNFS/repos/turbo-repo/node_modules/.pnpm/sqlite3@3.1.13/node_modules/sqlite3/lib/binding/node-v120-linux-x64/node_sqlite…
│ node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v120-linux-x64.tar.gz
│ (node:1115586) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
│ (Use `node --trace-deprecation ...` to show where the warning was created)
│ node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v120-linux-x64.tar.gz
│ node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v120-linux-x64.tar.gz 
│ node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@21.4.0 (node-v120 ABI) (falling back to source compile with node-gyp) 
│ node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v120-linux-x64.tar.gz 
│ node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v120-linux-x64.tar.gz 
│ node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@21.4.0 (node-v120 ABI) (falling back to source compile with node-gyp)

**Comment by rexdavid** [comment]
Just as a workaround , this cmd worked: pnpm add pilcrowOnPaper/arctic  🤷‍♂️

**Comment by pilcrowonpaper** [comment]
Probably unrelated to Arctic. Seems like an issue with `sqlite3` - which Oslo doesn't use

**Comment by vsantele** [comment]
I had the same issue, but I found the problem pretty easily.

There is a typo in your pnpm command.
The package name is arCtic with a C before the T.

artic is an old package: https://www.npmjs.com/package/artic

the correct command is `pnpm add arctic`
