### ISSUE TITLE
Feature Request: Start.gg Provider

### ISSUE THREAD

**Issue by Zeden19** [pilcrowonpaper/arctic#132]
Start.gg (previous smash.gg) recently released Oauth for their services.
https://developer.start.gg/docs/oauth/oauth-overview

This would be very useful for those working with e-sports (as start.gg hosts many in person e-sports tournaments).

**Comment by jadamita** [comment]
I can work on this if needed. @pilcrowOnPaper

**Comment by pilcrowonpaper** [comment]
Added in v2
