### ISSUE TITLE
Twitter authorization URL results in "Something Went Wrong" error

### ISSUE THREAD

**Issue by michaelyoon** [pilcrowonpaper/arctic#137]
I generate an authorization URL for Twitter like so:

```ts
const TWITTER_SCOPES = ['tweet.read', 'users.read', 'follows.read', 'follows.write'];

const state = generateState();
const codeVerifier = generateCodeVerifier();
const twitter = new Twitter(TWITTER_CLIENT_ID, TWITTER_CLIENT_SECRET, redirectURI);

const authUrl: URL = await twitter.createAuthorizationURL(state, codeVerifier, {
	scopes: TWITTER_SCOPES
});
```

When I click on that URL, I get this error:

<img width="495" alt="Screenshot 2024-06-06 at 3 10 44 PM" src="https://github.com/pilcrowOnPaper/arctic/assets/18614/8e4bd198-e24e-4f4b-8edf-2c7c4c6b847e">

I have double-checked my client ID and client secret in the Developer Portal.

I have also verified that my Callback URI is set correctly in the Portal:

<img width="557" alt="Screenshot 2024-06-06 at 3 12 59 PM" src="https://github.com/pilcrowOnPaper/arctic/assets/18614/5ec55f8a-73b0-4d24-9250-0f80e31cfdc1">

Any suggestions on how to troubleshoot this would be much appreciated.

Thanks in advance.

**Comment by pilcrowonpaper** [comment]
Does your `redirect_uri` match the callback URI 1:1? If `TWITTER_CLIENT_ID` is an env var, is it actually defined?

**Comment by michaelyoon** [comment]
Thanks for getting back to me. I just came back here to ask you to close the issue, because I realized that my `redirect_uri` was missing the port number. Sorry, my dumb mistake. Closing this now.
