### ISSUE TITLE
invalid_grant when using also for google oauth #78

### ISSUE THREAD

**Issue by francelwebdev** [pilcrowonpaper/arctic#142]
![Screenshot from 2024-06-18 13-10-07](https://github.com/pilcrowOnPaper/arctic/assets/18377068/7fe597de-0ae8-40ab-9782-78f2ba0923ef)

**Comment by pilcrowonpaper** [comment]
I highly doubt that this an issue with Arctic. Invalid grant is a catch-all error. Check that your client ID, client secret, and redirect URIs are actually defined and matches the one in the console. Make sure your code verifier is also correct. I can't help further without any code

**Comment by francelwebdev** [comment]
Hi @pilcrowOnPaper 

here is the code, I still have the same error.
google client Id, google clientSecret and redirectUri are well defined and correct.

![Screenshot from 2024-06-19 14-12-20](https://github.com/pilcrowOnPaper/arctic/assets/18377068/da42860a-49d1-4516-b76c-09cf63b93066)

**Comment by Kareem-Medhat** [comment]
I faced this issue and turns out I had the code verifier cookie accidentally set to state instead of  the generated code verifier. Hope this helps
