### ISSUE TITLE
Salesforce Additional URLs

### ISSUE THREAD

**Issue by jawills** [pilcrowonpaper/arctic#148]
For the [Salesforce provider](https://github.com/pilcrowOnPaper/arctic/blob/main/src/providers/salesforce.ts), the token and authorize endpoints are hardcoded:
```ts
const authorizeEndpoint = "https://login.salesforce.com/services/oauth2/authorize";
const tokenEndpoint = "https://login.salesforce.com/services/oauth2/token";
```

There is a use case to pass in a dynamic base url, so a feature like providing a custom url, or toggle for the sandbox url is ideal. Ex:
```ts
var baseUrl = "https://login.salesforce.com";
if(isSandbox){
    baseUrl = "https://test.salesforce.com";
}
const authorizeEndpoint = baseUrl + "/services/oauth2/authorize";
const tokenEndpoint = baseUrl + "/services/oauth2/token";
```

Custom domains can also be passed, so it may be best to have an optional parameter in the `OAuth2ProviderWithPKCE` interface / contstuctor

**Comment by pilcrowonpaper** [comment]
We can add this in v2 - can you configure the path as well? i.e. are you limited to <domain>/services/oauth2/token or can you do something like <domain>/something-else/services/oauth2/token?

**Comment by jawills** [comment]
I don't believe you can configure the path. I can't see anywhere in the documentation that allows for this. There is the ability to run oauth through JWT.

Adding additional documentation for reference:
- [OAuth2](https://trailhead.salesforce.com/content/learn/projects/build-a-connected-app-for-api-integration/implement-the-oauth-20-web-server-authentication-flow)
- [JWT](https://trailhead.salesforce.com/content/learn/projects/build-a-connected-app-for-api-integration/implement-the-oauth-20-web-server-authentication-flow)

**Comment by pilcrowonpaper** [comment]
Thanks, will add this in v2!

**Comment by pilcrowonpaper** [comment]
Added in v2 beta

**Comment by jawills** [comment]
I can test this. Is there an easy way of updating & integrating w/ lucia to test?

**Comment by pilcrowonpaper** [comment]
Here's the v2 docs

https://arcticjs.dev/guides/migrate-v2
