### ISSUE TITLE
TypeError: RequestInit: duplex option is required when sending a body

### ISSUE THREAD

**Issue by francelwebdev** [pilcrowonpaper/arctic#149]
![Screenshot from 2024-06-30 16-30-45](https://github.com/pilcrowOnPaper/arctic/assets/18377068/43157d50-4871-493b-b599-50c8c92b42e5)

**Comment by pilcrowonpaper** [comment]
That's... weird. I believe the duplex stuff is when you send `ReadableStream` in `fetch()`, but we don't use `ReadableStream`

**Comment by francelwebdev** [comment]
I just follow the doc.

**Comment by francelwebdev** [comment]
@pilcrowOnPaper I tried with the next version of arctic arctic@next and it works fine now with no errors.

Thanks
