### ISSUE TITLE
conflicting dependencies, unable to install arctic

### ISSUE THREAD

**Issue by Boby900** [pilcrowonpaper/arctic#153]
I am unable to install arctic
`npm install arctic` is giving me this below error, PFA

https://github.com/Boby900/lucia-demo

![Screenshot (601)](https://github.com/pilcrowOnPaper/arctic/assets/111265239/9310a086-5be9-46fc-9d3c-5fda1a44ccfd)

**Comment by pilcrowonpaper** [comment]
Does just calling `npm install` cause the same error?

**Comment by Boby900** [comment]
I was able to install other packages using npm but not this one

**Comment by pilcrowonpaper** [comment]
Are you sure this is an issue with Arctic? It only has 1 dependency and that dependency is dependency-free. Seems like a React issue?

**Comment by Boby900** [comment]
@pilcrowOnPaper I am using the latest version of react and next.js 14, don't know what's causing that.
I tried adding the flag `--legacy-peer-drops` but that too is throwing an error.

![Screenshot (605)](https://github.com/pilcrowOnPaper/arctic/assets/111265239/24f80910-c2f6-4308-8d78-cf73f3677d84)

![Screenshot (604)](https://github.com/pilcrowOnPaper/arctic/assets/111265239/6bae595f-219d-4fec-b39a-d696ef22743d)

**Comment by pilcrowonpaper** [comment]
If `npm install` on its own isn't working, it's probably not an arctic issue.

**Comment by Boby900** [comment]
Okay, my bad, I thought it was coming from an Arctic.
