### ISSUE TITLE
Github provider error: Failed to parse response body

### ISSUE THREAD

**Issue by nipatiitti** [pilcrowonpaper/arctic#160]
Hi

I'm trying to get a project with Elysium, Lucia-auth and Arctic to run, but have run into problems with the github oauth provider from arctic.

I started by following [this tutorial ](https://lucia-auth.com/tutorials/github-oauth/sveltekit), but couldn't get the oauth to work. Then I udpated arctic to 2.0 but it still didn't work so I dig a bit deeper.

The error originates from [this line](https://github.com/pilcrowOnPaper/arctic/blob/4ca8d769f799f34d47b90b3f48765da49a7fdb6b/src/request.ts#L30) and it happens because the fetch to https://github.com/login/oauth/access_token returns 404. Looking at the docs [here](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github) github excepts the `code`, `client_id`, `client_secret` and optional `redirect_url` as query parameters in the url. Playing around with insomnia I found that if some of them are missing github returns 404.

For some reason Arctic tries to [send the credentials as a Basic auth header](https://github.com/pilcrowOnPaper/arctic/blob/4ca8d769f799f34d47b90b3f48765da49a7fdb6b/src/providers/github.ts#L31). By editing the code in my local node_modules to look like the `createAuthorizationURL` function [above](https://github.com/pilcrowOnPaper/arctic/blob/4ca8d769f799f34d47b90b3f48765da49a7fdb6b/src/providers/github.ts#L19), I get it to work as it should.

**Comment by nipatiitti** [comment]
Here is an example of the error message

```
26 |     let data;
27 |     try {
28 |         data = await response.json();
29 |     }
30 |     catch {
31 |         throw new Error("Failed to parse response body");
                   ^
error: Failed to parse response body
      at ./node_modules/arctic/dist/request.js:31:15
```

**Comment by nipatiitti** [comment]
Okay seems like the error only happens with bun runtime 🤔 Maybe there is  differences between bun and node fetch or Request implementations

**Comment by nipatiitti** [comment]
Okay I figured out why it doesn't work with `bun` but it's weird af 😮‍💨

I proxied the servers traffic and for some reason on my current project setup when trying to fetch the access token bun only sends an empty request wihtout headers or body, but node sends a full one.

However if I change:

```ts
export async function sendTokenRequest(request: Request): Promise<OAuth2Tokens> {
  let response: Response
  try {
    response = await fetch(request)
  } catch (e) {
    throw new ArcticFetchError(e)
  }
```

to

```ts
export async function sendTokenRequest(request: Request): Promise<OAuth2Tokens> {
  let response: Response
  try {
    response = await fetch(request.url, {
      method: request.method,
      headers: request.headers,
      body: request.body,
    })
  } catch (e) {
    throw new ArcticFetchError(e)
  }
```
it works just fine 🫠

I also tested it with arctic alone by just git cloning, checking out to v2, and adding this to index.ts: 
```ts
const github = new GitHub("client-id", "client-secret", "redirect-uri");
github.validateAuthorizationCode("code")
```
running it with `bun src/index.ts` and it works just fine.

So I'm closing this issue because it clearly isn't problem with the arctic library but somewhere else in my setup. Maybe vite or svelte-kit is somehow messing with the fetch element :upside_down_face:

**Comment by pilcrowonpaper** [comment]
Ughh, this is caused by https://github.com/oven-sh/bun/issues/11381
