### ISSUE TITLE
Missing field `refresh_token_expires_in` for Keycloak in V2

### ISSUE THREAD

**Issue by malmz** [pilcrowonpaper/arctic#165]
OAuthToken class looks for `refresh_token_expires_in` for all providers. Keycloak uses `refresh_expires_in` for refresh token expiration. This has regressed since V1

**Comment by pilcrowonpaper** [comment]
"Fixed" by removing `refreshTokenExpiresInSeconds()` and `refreshTokenExpiresAt()` in the latest beta
