### ISSUE TITLE
Discord - [OAuth2RequestError] Missing "code_verifier" in OAuth request

### ISSUE THREAD

**Issue by hi-zp** [pilcrowonpaper/arctic#167]
```json
{
      "type": "OAuth2RequestError",
      "message": "invalid_request",
      "stack":
      "request": {},
      "description": "Missing \"code_verifier\"",
      "originalLine": 107,
      "originalColumn": 10
    }
```

**Comment by pilcrowonpaper** [comment]
Discord, officially, doesn't support PKCE. Is your client secret defined?

**Comment by dchcs** [comment]
Want to share a potential fix in case anyone else finds this issue with the same problem I had.

I was getting the missing code verifier error while following the Discord example, calling validateAuthorizationCode() like so:
```js
const tokens = await discord.validateAuthorizationCode(code);
```
After I started using null for the code verifier parameter, the error stopped occurring:
```js
const tokens = await discord.validateAuthorizationCode(code, null);
```
