### ISSUE TITLE
Rollup failed to resolve import "@oslojs/jwt"

### ISSUE THREAD

**Issue by bitsmakerde** [pilcrowonpaper/arctic#180]
I get in V2 this build error if I want build my app with vite and astro.

I use only GitHub and my self created Etsy provider. I don't usweapple

`13:18:28 [ERROR] [vite] x Build failed in 309ms
[vite]: Rollup failed to resolve import "@oslojs/jwt" from "/Users/andre/Projekte/JS/mrbiber/node_modules/arctic/dist/providers/apple.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external``

**Comment by pilcrowonpaper** [comment]
Works fine on my Astro project. Probably your "self created Etsy provider" is causing issues

**Comment by bitsmakerde** [comment]
I missed the re run of "nom i" after switching from 1.9.x to 2.0.x. it works all great plus the etsy provider
