### ISSUE TITLE
yahoo provider docs page shows examples that use code verifier while the real code does not support it.

### ISSUE THREAD

**Issue by zeronumbers** [pilcrowonpaper/arctic#185]
https://github.com/pilcrowonpaper/arctic/blob/cb736d17f584617c2de5dd45f91baca02a34f6c3/src/providers/yahoo.ts#L19

https://github.com/pilcrowonpaper/arctic/blob/cb736d17f584617c2de5dd45f91baca02a34f6c3/docs/pages/providers/yahoo.md?plain=1#L85

There are more lines like that.

It was changed here apparently:

https://github.com/pilcrowonpaper/arctic/pull/147/commits/bb16ec9b765af147d8c8bd0adae1bdaebd6a7eff

**Comment by pilcrowonpaper** [comment]
Thanks!
