### ISSUE TITLE
Custom Provider

### ISSUE THREAD

**Issue by tcurdt** [pilcrowonpaper/arctic#191]
I need to add a custom provider - but there are no docs/examples and some functions are not exported

```
import { createS256CodeChallenge } from "../oauth2.js";
import { createOAuth2Request, sendTokenRequest, sendTokenRevocationRequest } from "../request.js";
```

https://github.com/pilcrowonpaper/arctic/blob/82b3b208efbd9a7feb0c7a242f1cc427fb55e16d/src/providers/google.ts#L1C1-L2C99

I guess this would work

```
import { createS256CodeChallenge } from "arctic/dist/oauth2";
import { createOAuth2Request, sendTokenRequest, sendTokenRevocationRequest } from "arctic/dist/request";
```

...but is this the intended way?

**Comment by pilcrowonpaper** [comment]
Arctic does not provide APIs for creating custom providers and we don't intend to.

**Comment by tcurdt** [comment]
Well, the above works. It would be a little less awkward if the functions were exported in the `index.ts`.
That would be a tiny change. But well... if that's not wanted it sounds like I should better look for a different oauth library.
