### ISSUE TITLE
how do I redirect to /app, not root?

### ISSUE THREAD

**Issue by maxcli** [pilcrowonpaper/arctic#209]
Github object created using client ID. 

Problem : this url does not include the redirecto /app  . Instead it goes to /root .How do I get the /app ?
`const url= await github.createAuthorizationURL(state,[] );`

 

Note :   the google method signature is different, and does return the /app as I expected
example 
```
	const url = await google.createAuthorizationURL(state, codeVerifier, {
		scopes: ['profile', 'email']
	});
```

**Comment by pilcrowonpaper** [comment]
You pass the redirect URI when initializing `GitHub`

```ts
const github = new GitHub(clientId, clientSecret, redirectURI);
```

You also define the redirect URI when registering your app on GitHub's developer settings

**Comment by maxcli** [comment]
Thanks for that. I ended up using  the app registration like this http://localhost:5173/login/github/callback?redirectTo=/app
It is limited to just one route, but easier than changing my auth.ts code
