### ISSUE TITLE
Apple requires response_mode to be form_post when requesting email or name scopes

### ISSUE THREAD

**Issue by markusahlstrand** [pilcrowonpaper/arctic#214]
I just upgraded to arctic v2 and noticed that the apple integration isn't using the form_post which we need as we are requesting the user email.

<img width="592" alt="Screenshot 2024-11-24 at 00 04 51" src="https://github.com/user-attachments/assets/242543f0-1824-44a4-bcb3-75c7cfb168e6">

**Comment by pilcrowonpaper** [comment]
This is expected behavior. 

https://arcticjs.dev/providers/apple

**Comment by markusahlstrand** [comment]
Sorry, I’m not sure I follow. It seems that Apple requires the response_mode to be set to form_post for the authorization request to be accepted. However, with the current implementation, I don’t see a way to set this directly, other than modifying the authorizationUrl manually after it is generated. Is there another way to achieve this, or could this be a potential enhancement?

**Comment by pilcrowonpaper** [comment]
Yes, you're expected to set the query manually:

```ts
const url = apple.createAuthorizationURL(state, scopes);
url.searchParams.set("response_mode", "form_post");
```

I've add the code example to the docs.
