### ISSUE TITLE
Finding user's picture from Google Provider

### ISSUE THREAD

**Issue by daniellovera** [pilcrowonpaper/arctic#223]
Hi, I'm upgrading to 2.3 from 1.9.1 and not sure if I'm misunderstanding arctic/oslo or if what I'm trying to do isn't possible.

It looks like with 2.3 the decodeIdToken() function would save me a fetch call. However, I cannot find picture in the return.

Building the url as below:
`if (provider instanceof Google) {
			let scopes = ['profile', 'email']
			const url = provider.createAuthorizationURL(state, codeVerifier, scopes)
			return redirect(303, url)
		}
`

Post callback I get the token with:
`const tokens = await provider.validateAuthorizationCode(
				code,
				codeVerifier,
			)`

Then when I decode and log it with
`const claims = decodeIdToken(tokens.idToken())
			console.log(claims)`

I get 
{
  iss: 'https://accounts.google.com',
  azp: 'x.apps.googleusercontent.com',
  aud: 'x.apps.googleusercontent.com',
  sub: 'x',
  hd: 'example.com',
  email: 'email@domain',
  email_verified: true,
  at_hash: 'x',
  name: 'John Doe',
  given_name: 'John',
  family_name: 'Do',
  iat: x,
  exp: x
}

And then if I do the fetch:
`const userDetails = await fetch(
				'https://openidconnect.googleapis.com/v1/userinfo',
				{
					headers: { Authorization: 'Bearer ${tokens.accessToken()}' },
				},
			)
				.then((response) => response.json())
				.then((data: GoogleUserResponse) => data)
			console.log(userDetails)`

I get:

{
  sub: 'same x as above',
  name: 'John Doe',
  given_name: 'John',
  family_name: 'Do',
  picture: 'valid url',
  email: 'email@domain',
  email_verified: true,
  hd: 'example.com'
}

For reference, GoogleUserResponse is just
`export type GoogleUserResponse = {
  sub: string
  name?: string
  picture?: string
  email: string
  email_verified: boolean
  locale?: string
}`

so it's not adding anything to userDetails.

Was hoping you could help me understand if decodeIdToken() or something else in the Arctic/Oslo chain is stripping out the picture, since per https://developers.google.com/identity/openid-connect/openid-connect#an-id-tokens-payload the picture is part of the idToken.

Thanks again!

**Comment by daniellovera** [comment]
Nevermind, I missed that scopes have to be set with openid first for google, as in `let scopes = ['openid', 'profile', 'email']`

I'm getting the picture through now.

There's still a weird issue where the idToken for a gmail user has a picture claim when I decode the token but the idToken of a google workspace user does not, however I'm sure that's not due to anything related to arctic. But I'll leave this note here in case anyone else experiences weird issues with picture showing up in ID tokens only some of the time.

**Comment by pilcrowonpaper** [comment]
Arctic doesn't add any optional claims by default, so likely not an issue with Arctic
