### ISSUE TITLE
myAnimeList code_challenge_method only accepts plain

### ISSUE THREAD

**Issue by EduartePaiva** [pilcrowonpaper/arctic#225]
I was implementing myAnimeList provider and was getting an error from the API. It turned out that checking the myAnimeList [docs](https://myanimelist.net/apiconfig/references/authorization#step-2-client-requests-oauth-20-authentication) currently it only accepts the plain method for the code_challenge_method, the solution would be to just change `CodeChallengeMethod.S256` to `CodeChallengeMethod.Plain`. If you wish I can open a pull request for that.

Another solution would be `createAuthorizationURL` accept the code challenge method, in this particular case

**Comment by pilcrowonpaper** [comment]
Thanks, fixed with 2.3.2
