### ISSUE TITLE
always set client_id when validating the authorization code

### ISSUE THREAD

**Issue by joejemmely** [pilcrowonpaper/arctic#230]
According to https://datatracker.ietf.org/doc/html/rfc7636#section-4.3 the request for validating the authorization code should always include the `client_id`

**Comment by joejemmely** [comment]
#231

**Comment by pilcrowonpaper** [comment]
Are you sure that's the correct RFC? It doesn't say anything about `client_id`

**Comment by joejemmely** [comment]
The RFC for PKCE says the following:
> The client sends the code challenge as part of the OAuth 2.0 Authorization Request ([Section 4.1.1 of [RFC6749]](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1)) using the following additional parameters:

From my understanding, by `using the following additional parameters` it means all the params from the authorization request from https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.1 where `client_id` is marked as required, plus `code_challenge` and optionally `code_challenge_method`

**Comment by pilcrowonpaper** [comment]
Authorization request is different from the token request (which is where the authorization code is used).

> Upon receipt of the Authorization Code, the client sends the Access Token Request to the token endpoint.  In addition to the parameters defined in the OAuth 2.0 Access Token Request ([Section 4.1.3 of [RFC6749]](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3)), it sends the following parameter:
>
> code_verifier
>   REQUIRED.  Code verifier

And here's the relevant part of RFC 6749:

> client_id
> REQUIRED, if the client is not authenticating with the authorization server as described in [Section 3.2.1](https://datatracker.ietf.org/doc/html/rfc6749#section-3.2.1).

**Comment by joejemmely** [comment]
You are absolutely right! It looks like the provider I'm using isn't fully compliant I'm afraid. I was able to workaround the issue by extending the class and writing a custom method to validate the auth code. Would it make sense to expose all the functions from the `./request.ts` file in the main module so that consumers of the lib can use them to write custom provider logic?

**Comment by pilcrowonpaper** [comment]
No, because that would mean the new APIs would have to follow semantic versioning. The stuff in `request.ts` is simple. You don't need a library for it.
