### ISSUE TITLE
Apple's OAuth client's `validateAuthorizationCode` lacks code verifier argument

### ISSUE THREAD

**Issue by VityaSchel** [pilcrowonpaper/arctic#232]
It looks from [arctic documentation](https://arcticjs.dev/providers/apple) that code verifier argument should be implemented:

<img width="706" alt="изображение" src="https://github.com/user-attachments/assets/4f4faada-2338-4e8e-9bbb-bfa47bfeb43f" />

However both javascript implementation and typescript definitions lack second parameter:

<img width="666" alt="изображение" src="https://github.com/user-attachments/assets/15c8108a-02f5-44d1-b5af-c5be25094937" />
<img width="647" alt="изображение" src="https://github.com/user-attachments/assets/66a08fbd-50cb-4b11-8fea-7c3d85e1782b" />

**Comment by VityaSchel** [comment]
Does Apple support code verifier at all? I can't find it there https://developer.apple.com/documentation/sign_in_with_apple/generate_and_validate_tokens 
Looks like other providers extend from OAuth2Client class which sets "code_verifier" to body and then sends that to the provider's API, but Apple's provider does not implement that

**Comment by pilcrowonpaper** [comment]
That's a mistake in the documentation. Thanks for reporting the issue

**Comment by pilcrowonpaper** [comment]
Fixed with #233
