### ISSUE TITLE
cryto is not defined in the production

### ISSUE THREAD

**Issue by Boby900** [pilcrowonpaper/arctic#240]
cryto is not defined in the production and it's causing my prod env to crash,
![Screenshot (20)](https://github.com/user-attachments/assets/3d9ab136-6519-45c2-aaaa-18642de084be)

**Comment by pilcrowonpaper** [comment]
What version of Node are using (assuming you're using Node)? Use Node >=20 or polypill WebCrypto (see https://arcticjs.dev)

**Comment by Boby900** [comment]
it worked, though I had to specify engine in my package.json file

```json
 "engines": {
  "node": ">=22.0.0"
},
```

thanks @pilcrowonpaper
