### ISSUE TITLE
Add nonce to AppleIdTokenClaims

### ISSUE THREAD

**Issue by rmarscher** [pilcrowonpaper/arctic#3]
Not sure if you omitted nonce and nonce_supported on purpose. I have some native app code that uses the nonce and noticed it was missing when I switched to arctic on my server.

Looking for 

```ts
  nonce?: string;
  nonce_supported?: boolean;
```

to be present at

https://github.com/pilcrowOnPaper/arctic/blob/cf8dea553cccfe12d206b01efbe1020e4a938ae2/src/providers/apple.ts#L107-L118

https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/authenticating_users_with_sign_in_with_apple#3383773

Thanks again!

**Comment by pilcrowonpaper** [comment]
Fixed with `0.3.5`
