### ISSUE TITLE
Google provider scopes documentation

### ISSUE THREAD

**Issue by KLewin23** [pilcrowonpaper/arctic#34]
The docs show scopes being added in the instatiation of the google provider but from what I can tell looking around, it should be provided only on the `createAuthorizationURL` method.

![image](https://github.com/pilcrowOnPaper/arctic/assets/26819329/96ebd9c9-83af-4233-b9d0-b0c25340bff8)

I would open a pr but ive not used malta so im not sure exactly how to edit the site, I assume its just changing the google.md file

**Comment by pilcrowonpaper** [comment]
Fixed!
