### ISSUE TITLE
Github PKCE?

### ISSUE THREAD

**Issue by skyf0l** [pilcrowonpaper/arctic#43]
Is there a reason why PKCE is not implemented for the Github provider?

**Comment by LinusOP** [comment]
Github does not currently support PKCE. See bottom of the [OAuth apps docs](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps#1-request-a-users-github-identity) step 1.

**Comment by pilcrowonpaper** [comment]
What @LinusOP said

**Comment by mqnu00** [comment]
github 目前已支持 PKCE，看上去还没适配吗？
