### ISSUE TITLE
Refreshing tokens not working for Spotify provider

### ISSUE THREAD

**Issue by dukesteen** [pilcrowonpaper/arctic#59]
Refreshing tokens using `refreshAccessToken()` is not working for the Spotify provider as the client secret is not being passed to the underlying refresh function. 

# Proposed fix
Change https://github.com/pilcrowOnPaper/arctic/blob/main/src/providers/spotify.ts#L45 to include `{credentials: this.clientSecret}`

**Comment by pilcrowonpaper** [comment]
Fixed with #60
