### ISSUE TITLE
[Bug/Github]: Request forbidden by administrative rules. 

### ISSUE THREAD

**Issue by dinwwwh** [pilcrowonpaper/arctic#6]
![image](https://github.com/pilcrowOnPaper/arctic/assets/64189902/c50371c5-8ca1-4431-b420-2ebf987db086)

Indicate `arctic` forgot add user-agent to header inside `getUser` method

```ts
      const userGithub = (await fetch('https://api.github.com/user', {
        headers: {
          Authorization: `Bearer ${tokens.accessToken}`,
          'user-agent': 'arctic',
        },
      }).then(async (res) => res.json())) as any
```

**Comment by pilcrowonpaper** [comment]
This was an issue with Oslo, and it should be fixed with the latest version `0.4.1`
