### ISSUE TITLE
[BUG] spotify.validateAuthorizationCode(code) return Error 405: Method Not Allowed

### ISSUE THREAD

**Issue by Thomasevano** [pilcrowonpaper/arctic#74]
I followed the docs to implement Spotify OAuth with Arctic and Multiple OAuth providers with Lucia and when using the `spotify.validateAuthorizationCode(code)` function to get the tokens, I have a 405 error `Method Not Allowed`

![Capture d’écran 2024-02-20 à 14 21 05](https://github.com/pilcrowOnPaper/arctic/assets/22095896/640a6b04-734c-4b28-8149-47ddbdbf174c)

I used the code from the [Spotify documentation](https://developer.spotify.com/documentation/web-api/tutorials/code-flow) and it works:
```ts
const response = await fetch('https://accounts.spotify.com/api/token', {
	method: 'POST',
	headers: {
		'Content-Type': 'application/x-www-form-urlencoded',
		Authorization: `Basic ${VITE_BASIC_TOKEN}`
	},
	body: new URLSearchParams({
		code: code || '',
		redirect_uri: `${VITE_BASE_URL}/login/spotify/callback`,
		grant_type: 'authorization_code',
		code_verifier: storedState || '',
		client_id: VITE_SPOTIFY_CLIENT_ID
	})
});
const tokens = await response.json();
```

**Comment by pilcrowonpaper** [comment]
Can you share how you were initializing `new Spotify()`? In your code, which uses PKCE, client secret (the `Authorization` header part) isn't required so my guess is that something was wrong with your credentials.

**Comment by Thomasevano** [comment]
> Can you share how you were initializing `new Spotify()`? In your code, which uses PKCE, client secret (the `Authorization` header part) isn't required so my guess is that something was wrong with your credentials.

Thank you for your quick answer, i did like in the Arctic doc

<img width="573" alt="Capture d’écran 2024-02-20 à 23 42 24" src="https://github.com/pilcrowOnPaper/arctic/assets/22095896/5cc30921-e3a9-4ffc-a23d-3685cbe6d8b8">

**Comment by pilcrowonpaper** [comment]
Can you double check that those env vars are defined? Also, how were you able to get the response?

**Comment by Thomasevano** [comment]
> Can you double check that those env vars are defined? Also, how were you able to get the response?

They are defined when i pass them in `new Spotify()`. the variable `spotify` have them, the function `createAuthorizationURL()` is working I pass the state and the scopes. you mean the error message i posted ?

**Comment by pilcrowonpaper** [comment]
Yeah the `Response` object with the error message

**Comment by Thomasevano** [comment]
> Yeah the `Response` object with the error message

Just with a `console.log`
```js
const tokens = await spotify.validateAuthorizationCode(code)
console.log({tokens})
```

**Comment by pilcrowonpaper** [comment]
Did you manually edit the `node_modules` to add a console log?

**Comment by Thomasevano** [comment]
> Did you manually edit the `node_modules` to add a console log?

Yes, you are right. sorry for the misunderstanding, did it some time ago and forgot what I did exactly to debug. So I have redone the path I did while finding where the error came from and digging in the library code, I found that these functions are in your other library Oslo, so maybe I should have posted the issue there.
But since it concerns Spotify for me, I supposed maybe it didn't concern other providers, and here is more adapted. I indeed added a `console.log({response})` in [oslo/oauth2/index.js, between line 126-127](https://github.com/pilcrowOnPaper/oslo/blob/10119c54b62afffc0ed67ffecbff22cc14eac227/src/oauth2/index.ts#L126)

That is how I got the error message. maybe I did something wrong in my implementation, but I just followed the examples in the doc for GitHub OAuth, multi OAuth provider and Spotify OAuth.

**Comment by pilcrowonpaper** [comment]
Does your code work if you remove `code_verifier` and `code_challenge` from both the authorization URL and token request?

**Comment by Thomasevano** [comment]
> Does your code work if you remove `code_verifier` and `code_challenge` from both the authorization URL and token request?

It works without `code_verifier` in the token request. To create authorization URL, the code from the docs works:
```js
const url = await spotify.createAuthorizationURL(state, {scopes});
```

**Comment by pilcrowonpaper** [comment]
So this works?

```ts
const response = await fetch('https://accounts.spotify.com/api/token', {
	method: 'POST',
	headers: {
		'Content-Type': 'application/x-www-form-urlencoded',
		Authorization: `Basic ${VITE_BASIC_TOKEN}`
	},
	body: new URLSearchParams({
		code: code || '',
		redirect_uri: `${VITE_BASE_URL}/login/spotify/callback`,
		grant_type: 'authorization_code',
		client_id: VITE_SPOTIFY_CLIENT_ID
	})
});
```

**Comment by pilcrowonpaper** [comment]
Yeah tested out and it works fine on my end

**Comment by Thomasevano** [comment]
> So this works?
> 
> ```ts
> const response = await fetch('https://accounts.spotify.com/api/token', {
> 	method: 'POST',
> 	headers: {
> 		'Content-Type': 'application/x-www-form-urlencoded',
> 		Authorization: `Basic ${VITE_BASIC_TOKEN}`
> 	},
> 	body: new URLSearchParams({
> 		code: code || '',
> 		redirect_uri: `${VITE_BASE_URL}/login/spotify/callback`,
> 		grant_type: 'authorization_code',
> 		client_id: VITE_SPOTIFY_CLIENT_ID
> 	})
> });
> ```

Yes

**Comment by pilcrowonpaper** [comment]
Unless I can get a minimal reproduction, I don't think I can help much since it works fine on my end. Something's probably wrong with your client ID, client secret, redirect URI, and/or authorization code.

**Comment by steele123** [comment]
I think this is a bun related issue, using the discord oauth client I receive the same error, the it appears to be a bug with bun's Request object not using the proper method

broken:
```js
const request = new Request(this.tokenEndpoint, {
   method: "POST",
   headers,
   body
});

fetch(request);
```

working:
```js
const response = await fetch(this.tokenEndpoint, {
   method: "POST",
   headers,
   body
});
```

if you run the broken code on bun you will receive a 405, so my assumption is some bun bug doesn't pass the req method correctly and it just uses a get request... ( i modified this in node_modules/arctic/node_modules/oslo/dist/oauth2/index.js:106:9 )

**Comment by steele123** [comment]
> Unless I can get a minimal reproduction, I don't think I can help much since it works fine on my end. Something's probably wrong with your client ID, client secret, redirect URI, and/or authorization code.

to reproduce, using bun v1.0.29, svelte, arctic 1.1.4, discord oauth

**Comment by steele123** [comment]
also to note, the code works perfectly fine using node, but breaks when using bun

**Comment by steele123** [comment]
this is also a working fix

```js
const response = await fetch(request, {
   method: "POST",
});
```

**Comment by steele123** [comment]
https://github.com/pilcrowOnPaper/oslo/pull/53

**Comment by Thomasevano** [comment]
> I think this is a bun related issue, using the discord oauth client I receive the same error, the it appears to be a bug with bun's Request object not using the proper method
> 
> broken:
> 
> ```js
> const request = new Request(this.tokenEndpoint, {
>    method: "POST",
>    headers,
>    body
> });
> 
> fetch(request);
> ```
> 
> working:
> 
> ```js
> const response = await fetch(this.tokenEndpoint, {
>    method: "POST",
>    headers,
>    body
> });
> ```
> 
> if you run the broken code on bun you will receive a 405, so my assumption is some bun bug doesn't pass the req method correctly and it just uses a get request... ( i modified this in node_modules/arctic/node_modules/oslo/dist/oauth2/index.js:106:9 )

Oh nice catch, I'm using Bun too, first project I am using it, and haven't thought about that possibility. Maybe it's a bit too soon to try bun on projects even after 1.0 then 😅.

**Comment by pilcrowonpaper** [comment]
Closing this since this is an issue with Oslo, rather than Arctic, and more importantly, it's a bug with Bun
